import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from "@react-email/components";

interface DonationReceiptEmailProps {
  donorName: string;
  organizationName: string;
  amount: string;
  donationDate: string;
  paymentMethod?: string;
  campaignName?: string;
  isTaxDeductible: boolean;
  ein?: string;
}

export function DonationReceiptEmail({
  donorName,
  organizationName,
  amount,
  donationDate,
  paymentMethod,
  campaignName,
  isTaxDeductible,
  ein,
}: DonationReceiptEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>
        Donation receipt from {organizationName} — {amount}
      </Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={heading}>Donation Receipt</Heading>
          <Text style={greeting}>Dear {donorName},</Text>
          <Text style={paragraph}>
            Thank you for your generous contribution to{" "}
            <strong>{organizationName}</strong>. Your support makes a real
            difference.
          </Text>

          <Section style={detailsSection}>
            <Text style={detailRow}>
              <strong>Amount:</strong> {amount}
            </Text>
            <Text style={detailRow}>
              <strong>Date:</strong> {donationDate}
            </Text>
            {paymentMethod && (
              <Text style={detailRow}>
                <strong>Payment Method:</strong> {paymentMethod}
              </Text>
            )}
            {campaignName && (
              <Text style={detailRow}>
                <strong>Campaign:</strong> {campaignName}
              </Text>
            )}
          </Section>

          <Hr style={hr} />

          {isTaxDeductible ? (
            <Section>
              <Text style={taxNotice}>
                {organizationName} is a 501(c)(3) tax-exempt organization
                {ein ? ` (EIN: ${ein})` : ""}. No goods or services were
                provided in exchange for this contribution. Please retain this
                receipt for your tax records.
              </Text>
            </Section>
          ) : (
            <Section>
              <Text style={taxNotice}>
                This donation may not be tax-deductible. Please consult your tax
                advisor for guidance.
              </Text>
            </Section>
          )}

          <Text style={paragraph}>
            A PDF copy of your tax receipt is attached to this email. You can
            also download receipts at any time from your donations page.
          </Text>

          <Text style={footer}>
            This receipt was generated by RadBooks on behalf of{" "}
            {organizationName}.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

const main = {
  backgroundColor: "#f6f9fc",
  fontFamily:
    '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
};

const container = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "40px 48px",
  borderRadius: "8px",
  maxWidth: "580px",
};

const heading = {
  fontSize: "24px",
  fontWeight: "700" as const,
  color: "#1a1a1a",
  marginBottom: "24px",
};

const greeting = {
  fontSize: "16px",
  color: "#333333",
  marginBottom: "4px",
};

const paragraph = {
  fontSize: "14px",
  lineHeight: "24px",
  color: "#555555",
};

const detailsSection = {
  backgroundColor: "#f9fafb",
  borderRadius: "6px",
  padding: "16px 20px",
  margin: "20px 0",
};

const detailRow = {
  fontSize: "14px",
  color: "#333333",
  margin: "6px 0",
};

const hr = {
  borderColor: "#e5e7eb",
  margin: "24px 0",
};

const taxNotice = {
  fontSize: "12px",
  lineHeight: "20px",
  color: "#666666",
  fontStyle: "italic" as const,
};

const footer = {
  fontSize: "11px",
  color: "#999999",
  marginTop: "32px",
};
